function mh_figpreppdf(figH)
% MH_FIGPREPPDF:  common plot fixups for pdf export

axH = findobj(figH, 'Type', 'axes');

set(axH, .... 
    'TickDir', 'out', ...
    'TickLength', 0.012*[1 1], ...
    'Box', 'on', ...
    'LineWidth', 0.25, ...
    'FontName', 'Arial', ...
    'FontSize', 7);

tH = findall(gcf, 'Type', 'text');
set(tH, 'FontName', 'arial', ...
    'fontsize', 8);

