function rgb = misccolors(inId)
%MISCCOLORS (tools-mh): return RGB triplets for color strings
%

% MH 150708 created


% MH: these are my shorthands so names may not be accurate
colorNamesRgbs = { ...
    'Orange', [1.0 0.5 0.2]; ...
    'DarkOrange', [0.75 0.5 0.22]; ...
    'DarkCyan',  [0 153 153]/255 };

% add unq13 colors to the table
unq13ColorNames = { 
    'VividGreen', ...
    'StrongPurplishPink', ...
    'StrongBlue', ...
    'VividYellowishGreen', ...
    'StrongViolet', ...
    'VividOrangeYellow', ...
    'StrongPurplishRed', ...
    'VividGreenishYellow', ...
    'StrongReddishBrown', ...
    'StrongYellowishPink', ...
    'DeepYellowishBrown', ...
    'VividReddishOrange', ...
    'DarkOliveGreen' };
uc = cmap_unique13;
for iU = 1:length(unq13ColorNames)
    colorNamesRgbs(end+1,1:2) = { unq13ColorNames{iU}, uc(iU,:) };
end

%%%%%%

% lookup name
matchIx = strcmp(lower(colorNamesRgbs(:,1)), lower(inId));
if sum(matchIx) == 0
    error('input string not found in this color list, you can add it');
elseif sum(matchIx) > 1
    error('bug');
end
    
rgb = colorNamesRgbs{matchIx,2};
